# Change these first
owner: shimuldn # Your GitHub organization or username, where this repository lives
repo: upptime-personal # The name of this repository

sites:
  - name: Whoogle Search - Personal
    url: $PERSONAL_WHOOGLE
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: Searx Search - Personal
    url: $SEARX_PERSONAL
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: Piped Youtube - Personal
    url: $PIPED_PERSONAL
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
    
  - name: Adguard DNS Ocean - Personal
    check: "tcp-ping"
    url: $DNS_OCEAN
    port: $DNS_OCEAN_PORT
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: Adguard DNS D - Personal
    check: "tcp-ping"
    url: $DNS_D
    port: $DNS_D_PORT
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: Adguard DNS P - Personal
    check: "tcp-ping"
    url: $DNS_P
    port: $DNS_P_PORT
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shimul.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Personal Access only"
  introMessage: Personal Apps
i18n:
  footer: Thank you.
theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
